"""Structural interfaces for trader.py's orchestrator. Implementations don't need to inherit
these — anything with matching methods satisfies them (see tests/fakes.py)."""
from typing import Iterable, Protocol


class DataProvider(Protocol):
    def get_closes(self, symbol: str) -> list[float]: ...
    def get_ltp(self, symbols: Iterable[str]) -> dict[str, float]: ...


class Broker(Protocol):
    def place_order(self, symbol: str, qty: int, side: str, price: float) -> int:
        """side is "BUY" or "SELL". Returns filled quantity (0 if none)."""
        ...


class Strategy(Protocol):
    def signal(self, closes: list[float]) -> bool: ...
    def features(self, closes: list[float]) -> dict: ...


class RiskManager(Protocol):
    def trading_halted(self) -> bool: ...
    def daily_loss_limit_hit(self, equity: float, day_start_equity: float) -> bool: ...
    def max_positions_reached(self, open_positions: dict) -> bool: ...
    def theme_limit_reached(self, open_positions: dict, src: str) -> bool: ...
    def position_size(self, cash: float, price: float) -> int: ...


class PortfolioStore(Protocol):
    def load(self) -> dict: ...
    def save(self, state: dict) -> None: ...


class Journal(Protocol):
    def record(self, **event: object) -> None: ...
